### ISSUE TITLE
dns and node

### ISSUE THREAD

**Issue by alex8900vbs** [Kale-Network/kale-blockchain#7]
2021-07-06T14:35:03.788 wallet kale.wallet.wallet_node    : WARNING  No keys present. Create keys with the UI, or with the 'kale keys' program.
2021-07-06T14:35:37.098 daemon asyncio                    : ERROR    Task exception was never retrieved
future: <Task finished name='Task-13' coro=<IocpProactor.accept.<locals>.accept_coro() done, defined at asyncio\windows_events.py:563> exception=OSError(22, 'Il nome di rete specificato non è più disponibile', None, 64, None)>
Traceback (most recent call last):
  File "asyncio\windows_events.py", line 566, in accept_coro
  File "asyncio\windows_events.py", line 812, in _poll
  File "asyncio\windows_events.py", line 555, in finish_accept
OSError: [WinError 64] Il nome di rete specificato non è più disponibile
2021-07-06T14:35:37.099 daemon asyncio                    : ERROR    Accept failed on a socket
socket: <asyncio.TransportSocket fd=824, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::1', 56300, 0, 0)>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 818, in loop
  File "asyncio\windows_events.py", line 566, in accept_coro
  File "asyncio\windows_events.py", line 812, in _poll
  File "asyncio\windows_events.py", line 555, in finish_accept
OSError: [WinError 64] Il nome di rete specificato non è più disponibile
2021-07-06T14:35:51.917 full_node kale.full_node.full_node: ERROR    Exception while querying DNS server: The DNS operation timed out after 30.003463745117188 seconds
2021-07-06T14:36:06.479 wallet kale.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:56300
2021-07-06T14:36:06.495 harvester kale.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:56300
2021-07-06T14:36:12.557 wallet kale.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:56300
2021-07-06T14:36:12.573 harvester kale.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:56300
2021-07-06T14:36:18.604 harvester kale.rpc.rpc_server     : WARNING  Cannot connect to daemon at ws://localhost:56300
2021-07-06T14:36:18.635 wallet kale.rpc.rpc_server        : WARNING  Cannot connect to daemon at ws://localhost:56300
2021-07-06T14:39:22.027 wallet kale.wallet.wallet_node    : WARNING  No keys present. Create keys with the UI, or with the 'kale keys' program.
2021-07-06T14:39:53.855 full_node kale.full_node.full_node: ERROR    Exception while querying DNS server: The DNS operation timed out after 30.000961780548096 seconds
2021-07-06T14:41:49.573 full_node kale.full_node.full_node: ERROR    Exception while querying DNS server: The DNS operation timed out after 30.014643669128418 seconds

how resolve this?

**Comment by kaleseed** [comment]
please try the new version.
